# Permalinks
permalink:           pretty

# Setup
title:               Lubna Alhenaki
tagline:             Passion in Data Analysis 
url:                 http://LubnaAlhenaki.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lubna Alhenaki
  url:               https://twitter.com/Lubna_sulieman
  email:             lubna.henaki@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://LubnaAlhenaki.com/zwmiller

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Projects: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-cayman
